spring.datasource.url=${RARETABLE_DATABASE_URL:jdbc:postgresql://localhost:5433/raretable}
spring.datasource.username=${RARETABLE_DATABASE_USERNAME:raretable}
spring.datasource.password=${RARETABLE_DATABASE_PASSWORD:raretable}

raretable.auth.siwe.domain=localhost:5173
raretable.auth.siwe.uri=http://localhost:5173
raretable.auth.siwe.allow-insecure-origin=true

server.servlet.session.cookie.secure=false
